### ISSUE TITLE
Upon submission of a quiz the 'add to quickbar' option appears even though the class is already pinned

### ISSUE THREAD

**Issue by jtd8414** [MatthewGalan/mycourses-plus#16]
I noticed that when I submit a quiz and am redirected to the quiz submission screen, myCoursesPlus prompts me to add the class to the quickbar even though it is already pinned. When I click the add option, the page reloads but nothing changes.

![image](https://user-images.githubusercontent.com/32747127/98492510-19077780-2206-11eb-885b-0ab189d63275.png)

**Comment by MatthewGalan** [comment]
Currently, we try to figure out which course you're on by looking at the URL. Apparently there's a whole bunch of edge cases with weird pages that don't show the course ID in the URL the way we expect.

In hindsight we should probably just scrape the current course ID from the header element at the top of the page, since I don't believe that changes at all from page to page.

**Comment by MattGalan** [comment]
@jtd8414 thanks for the bug report!

I believe the issue was this:
1. Quiz submission page has a weird URL
1. Code couldn't find the class ID from the URL
1. Code sees that class ID `undefined` hasn't been saved before
1. "Add to quick bar" button is rendered

I believe I fixed the issue in d8e6e3a976b92b0420a866cae67ee6ed6a7fa744 by adding a null check before step 3.

I don't have any quizzes to test this with right now, so let me know if it's fixed!

**Comment by jtd8414** [comment]
@MatthewGalan the behavior is now different but not fixed. It still lets me add the class, which it now successfully adds. But when I visit any of the pages I am met with a not authorized screen. Also for testing you don't need to take quiz, just viewing the feedback quiz page is adequate, see screenshots

Quiz Summary Url: `https://mycourses.rit.edu/d2l/lms/quizzing/user/quiz_summary.d2l?qi=866367&ou=838805`
![image](https://user-images.githubusercontent.com/32747127/98756817-4d5f6d00-2399-11eb-9044-91cdfcd5dd75.png)
![image](https://user-images.githubusercontent.com/32747127/98756853-5d774c80-2399-11eb-8357-64b9c97b0ce9.png)

**Comment by MattGalan** [comment]
I'm able to reproduce it on my end, thank you!

I think I got it for real this time, in 5873174b72f2bdc1e4da80c5e5157470769bde99. The trick was adding a `g` to the end of a regex pattern. Yes, one letter.

Let me know if it works for you, and thank you for your patience. :)

**Comment by jtd8414** [comment]
After taking a quiz I see that this bug has now resolved. Nice work.
